### ISSUE TITLE
Link to Autor doesn't work

### ISSUE THREAD

**Issue by simosechi** [IMAGINARY/pink-trombone#3]
The link in the readme that points to Neil Thapen's site doesn't work

**Comment by elondaits** [comment]
It does work for me, the address is:

http://venuspatrol.nfshost.com/

what might be happening (because it happened to me first) is that your browser is attempting to access the https version of the site, which does not work. Browsers sometimes try to automatically send you to the encrypted version, for security. In that case click on the address bar of your browser, change https:// to http:// and it should work. Our link is to the http version, so it's as good as we can make it.
